<div style="font-family:sarabun;font-size:16px;">
<p style="text-align: right;"><span style="font-weight: 400;">เลขที่...............</span> <strong>&nbsp;</strong>
<p style="text-align: center;"><strong>สัญญาตกลงการจ้างเหมาบริการ&nbsp;&nbsp;&nbsp;</strong>

<p style="text-align: justify;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; สัญญาตกลงการจ้างฉบับนี้ทำขึ้น ณ ..........................................................เลขที่ใบอนุญาต&nbsp; &hellip;&hellip;&hellip;&hellip;.....................................................&hellip;.. ตั้งอยู่เลขที่ .....................................
ถนน ............................ซอย................ ตำบล/แขวง................อำเภอ/เขต.......................จังหวัด....................รหัสไปรษณีย์............................เบอร์โทรสถานประกอบการ &hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip; เมื่อวันที่ &hellip;&hellip;&hellip;&hellip;&hellip;....&nbsp; ระหว่าง .................. โดย ...................................... ตำแหน่งเจ้าของสถานประกอบการ ซึ่งต่อไปนี้เรียกว่า &ldquo;ผู้ว่าจ้าง&rdquo; ฝ่ายหนึ่ง กับ </span><span style="font-weight: 400;">บริษัท ไอซี ควอลิตี้ซิสเท็ม จำกัด&nbsp; โดย นายนิติพัฒน์ วงศ์ศิริธร ผู้รับมอบอำนาจ&nbsp; สำนักงานตั้งอยู่เลขที่ 50/19 หมู่ที่ 6 ตำบลบางหลวง&nbsp; อำเภอเมืองปทุมธานี จังหวัดปทุมธานี 12000 โทรศัพท์ 02 - 1010325</span><span style="font-weight: 400;"> ซึ่งต่อไปนี้ในสัญญาเรียกว่า&nbsp; &ldquo;ผู้รับจ้าง&rdquo; อีกฝ่ายหนึ่ง คู่สัญญาทั้งสองฝ่ายได้ตกลงกันโดยมีสาระสำคัญ ดังต่อไปนี้</span>
<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>ข้อ 1 </strong><span style="font-weight: 400;">&ldquo;ผู้ว่าจ้าง&rdquo;&nbsp; ตกลงว่าจ้าง และ &ldquo;ผู้รับจ้าง&rdquo; ตกลงรับจ้างเหมาทำการเก็บขนย้ายและกำจัดขยะมูลฝอยติดเชื้อ&nbsp; ให้กับ &ldquo;ผู้ว่าจ้าง&rdquo; เพื่อให้การทำลายขยะดังกล่าวเป็นไปตามกฎกระทรวงสาธารณสุขว่าด้วยการกำจัดขยะมูลฝอยติดเชื้อ พ.ศ. 2545 และกฎหมายอื่นๆที่เกี่ยวข้อง &nbsp; ตามรายละเอียดแนบท้ายบันทึกที่แนบมาพร้อมนี้ </span><strong>&nbsp;</strong><span style="font-weight: 400;">โดยมีข้อกำหนดและเงื่อนไขแห่งบันทึกนี้ รวมทั้งเอกสารแนบท้ายบันทึกนี้</span>&nbsp;
<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>ข้อ 2</strong><span style="font-weight: 400;">&nbsp; &ldquo;ผู้รับจ้าง&rdquo; ตามข้อ 1 สัญญาว่าจะเริ่มนับตั้งแต่&nbsp; วันที่ ..................ถึงวันที่ .....................รวมระยะเวลา&nbsp; &nbsp; &nbsp; 12 เดือน ถ้าผู้รับจ้างมิได้ลงมือทำงานภายในกำหนดเวลา หรือมีเหตุให้เชื่อได้ว่าผู้รับจ้างไม่สามารถทำงานให้แล้วเสร็จภายในกำหนดเวลา&nbsp; หรือล่าช้าเกินกว่ากำหนดเวลา หรือผู้รับจ้างทำผิดข้อตกลงข้อใดข้อหนึ่ง ผู้ว่าจ้างมีสิทธิที่จะบอกเลิกจ้างตามบันทึกนี้ได้&nbsp;</span>
<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>ข้อ 3</strong><span style="font-weight: 400;">&nbsp; &ldquo;ผู้ว่าจ้าง&rdquo;&nbsp; ตกลงจ่าย และผู้รับจ้างตกลงรับเงินค่าจ้างเป็นราย รายครั้ง&nbsp; รวม 12 เดือน โดยกำหนดค่าจ้างตามน้ำหนักไม่เกิน 10 กิโลกรัมต่อครั้ง&nbsp; ปริมาณน้ำหนักขยะส่วนที่เกิน 10 กิโลกรัมขึ้นไป ทางบริษัทฯ จะคิดค่าขยะส่วนที่เกิน&nbsp; เพิ่มกิโลกรัมละ 15 บาท ขยะที่&ldquo;ผู้รับจ้าง&rdquo; เก็บขนย้ายไปทำลายในแต่ละเดือน คิดค่าจ้างเหมาในอัตราครั้งละ &hellip;&hellip;..บาท (&nbsp; จำนวนบาทถ้วนตัวอักษร.............) จัดเก็บ ............... ครั้งต่อ เดือน เป็นค่าจ้างรวมทั้งสิ้นต่อปี .............บาท ( บาทถ้วนตัวอักษร)&nbsp; </span><span style="font-weight: 400;">ราคานี้ยังไม่รวมภาษีมูลค่าเพิ่ม </span><span style="font-weight: 400;">&nbsp;7 %&nbsp; โดยกำหนดจ่ายภายใน&nbsp; 30 วัน นับตั้งแต่วันที่ &ldquo;ผู้ว่าจ้าง&rdquo; หรือตัวแทนของ</span> <span style="font-weight: 400;">&ldquo;ผู้ว่าจ้าง&rdquo;</span> <span style="font-weight: 400;">ได้ทำการตรวจรับถูกต้องเรียบร้อยแล้ว</span><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>ข้อ 4 หน้าที่รับผิดชอบของ &ldquo;ผู้รับจ้าง&rdquo;</strong>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4.1&nbsp; &ldquo;ผู้รับจ้าง&rdquo;&nbsp; จะต้องทำการเก็บขนย้ายและกำจัดขยะมูลฝอยติดเชื้อ โดยใช้พนักงานที่มีความรู้ผ่านการอบรมการกำจัดขยะติดเชื้อและขนย้าย&nbsp; เพื่อป้องกันอันตรายจาการเก็บขยะ และปฏิบัติตามหลักเกณฑ์ที่กฎหมายและระเบียบได้กำหนดไว้อย่างเคร่งครัด เพื่อให้เป็นไปตามกฎกระทรวงสาธารณสุขว่าด้วยการกำจัดขยะมูลฝอยติดเชื้อ พ.ศ. 2545<span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4.2&nbsp; &ldquo;ผู้รับจ้าง&rdquo; จะต้องเป็นผู้มีอาชีพรับจ้างขนและกำจัดขยะมูลฝอยติดเชื้อ ที่มีสถานที่ผู้ได้รับใบอนุญาตกำจัดขยะมูลฝอยติดเชื้อ ซึ่งเป็นนิติบุคคลผู้มีอาชีพรับจ้างกำจัดขยะมูลฝอยติดเชื้อ&nbsp; ไว้รองรับการกำจัดขยะมูลฝอยติดเชื้อ โดยวิธีเผาในเตาเผาขยะมูลฝอยติดเชื้อ ตลอดระยะเวลาตามสัญญานี้ด้วย</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;4.3&nbsp; &ldquo;ผู้รับจ้าง&rdquo; จะต้องทำการเก็บขนย้ายและกำจัดขยะมูลฝอยติดเชื้อ ในวันและเวลาตามตารางการจัดเก็บของ&nbsp; &ldquo;ผู้รับจ้าง&rdquo; ไปกำจัดตามวิธีการที่กำหนดและถูกต้อง ในการขนย้ายขยะฯดังกล่าวทุกครั้งจะต้องบันทึกปริมาณน้ำหนัก&nbsp;</span>

<p style="text-align: center;"><span style="font-weight: 400;">-2-</span>
<br><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ข้อ 5 หน้าที่รับผิดชอบของ &ldquo;ผู้ว่าจ้าง&rdquo;</strong>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 5.1&nbsp; &ldquo;ผู้ว่าจ้าง&rdquo; จะต้องจัดเก็บขยะมูลฝอยติดเชื้อที่บรรจุไว้ในถุงแดงอยู่ในสภาพเรียบร้อย ถุงไม่แตก ไม่รั่วซึม &nbsp; &nbsp; &nbsp; &nbsp; มัดปากถุงอย่างถูกต้อง และแยกของมีคมทุกชนิดบรรจุมิดชิดไม่ให้แทงทะลุออกจากถุง ไว้ที่จุดพักตามสถานที่พักขยะของ&ldquo;ผู้ว่าจ้าง&rdquo;&nbsp; โดยปฏิบัติให้เป็นไปตามประกาศกระทรวงสาธารณสุข และกฎหมายที่เกี่ยวข้องทุกประการ</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 5.2&nbsp; &ldquo;ผู้ว่าจ้าง&rdquo; จะต้องจัดเจ้าหน้าที่ผู้รับผิดชอบขยะมูลฝอยติดเชื้อไว้ ประสานงานและร่วมมือรับทราบการบันทึกน้ำหนักขยะ ตลอดจนการลงลายมือชื่อร่วมไว้ในเอกสารดังกล่าว ตามวันและเวลาที่ทั้งสองฝ่ายได้ตกลงกำหนดไว้ด้วย</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 5.3&nbsp; &ldquo;ผู้ว่าจ้าง&rdquo; จะต้องจัดเก็บขยะมูลฝอยติดเชื้อ ตามข้อ 5.1 ไว้ที่จุดพัก พักขยะซึ่ง &ldquo;ผู้รับจ้าง&rdquo; สามารถทำการเก็บขนได้ &nbsp; ตามวันและเวลาที่ทั้งสองฝ่ายได้ตกลงกำหนดกันไว้</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 5.4 หาก&rdquo;ผู้ว่าจ้าง&rdquo;เปิดทำการไม่ตรงเวลาทำการของ&rdquo;ผู้รับจ้าง&rdquo; หรือมีเหตุให้ต้องหยุดทำการในวันและเวลาที่ตกลงกันไว้ &ldquo;ผู้ว่าจ้าง&rdquo; จะต้องวางขยะ ไว้ในจุดที่ &ldquo;ผู้รับจ้าง&rdquo;สามารถเก็บขนได้ หาก &ldquo;ผู้ว่าจ้าง&rdquo;ไม่วางขยะตามกำหนดวันและเวลาที่ตกลงกันไว้&rdquo;ผู้ว่าจ้าง&rdquo;ยินยอมจ่ายค่าบริการให้ &ldquo;ผู้รับจ้าง&rdquo;</span>
<br><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ข้อ 6</strong><span style="font-weight: 400;">&nbsp; กรณี&ldquo;ผู้รับจ้าง&rdquo; ไม่ปฏิบัติตามข้อตกลงในสัญญานี้ข้อหนึ่งข้อใดด้วยเหตุใดๆก็ตามเป็นเหตุให้เกิดความเสียหายแก่&nbsp; &nbsp; &ldquo;ผู้ว่าจ้าง&rdquo; แล้ว &ldquo;ผู้รับจ้าง&rdquo; ยินดีรับผิดชอบ และยินยอมชดใช้ค่าเสียหาย อันเกิดจากการที่ &ldquo;ผู้รับจ้าง&rdquo; ไม่ปฏิบัติตามข้อตกลงนั้น ให้แก่ &ldquo;ผู้ว่าจ้าง&rdquo; โดยสิ้นเชิง&nbsp; ภายในกำหนด 30 วัน นับแต่วันที่ได้รับแจ้งจาก &ldquo;ผู้ว่าจ้าง&rdquo;</span>
<br><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ข้อ 7</strong><span style="font-weight: 400;">&nbsp; กรณีที่&ldquo;ผู้ว่าจ้าง&rdquo; ประสงค์จะบอกเลิกสัญญาฉบับนี้ก่อนกำหนด &ldquo;ผู้ว่าจ้าง&rdquo; จะต้องแจ้งให้ &ldquo;ผู้รับจ้าง&rdquo; ทราบล่วงหน้าไม่น้อยกว่า 30 วัน</span>
<br><span style="font-weight: 400;">สัญญาจ้างนี้ทำขึ้นสองฉบับ&nbsp; มีข้อความถูกต้องตรงกัน ทั้งสองฝ่ายได้อ่านและเข้าใจดีแล้ว&nbsp; จึงได้ลงลายมือชื่อพร้อมทั้งประทับตรา (ถ้ามี) ไว้ต่อหน้าพยานเป็นสำคัญและเก็บไว้ฝ่ายละฉบับ</span>
<br>&nbsp;
<br><span style="font-weight: 400;">&nbsp;</span><strong>หมายเหตุ</strong><span style="font-weight: 400;"> : ทาง &ldquo;ผู้รับจ้าง&rdquo; จะเข้าดำเนินการจัดเก็บขยะมูลฝอยติดเชื้อให้กับ &ldquo;ผู้ว่าจ้าง&rdquo; หลังจากทำสัญญาแล้วประมาณ 1 เดือน</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ชื่อผู้ประกอบการ &nbsp; ......................... ............... &nbsp; &nbsp; &nbsp; เบอร์โทรศัพท์.......................</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ชื่อผู้ประสานงาน (ผู้ติดต่อได้).............................. &nbsp; เบอร์โทรศัพท์ ........................</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; สถานที่ตั้ง</span> <span style="font-weight: 400;">N &hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&nbsp; &nbsp; &nbsp; &nbsp; E &hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;เวลาทำการ ..........................................................................................</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;สถานที่จัดเก็บ .....................................................................................</span>
<br>&nbsp;
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ลงชื่อ).........................................ผู้ว่าจ้าง</span> <span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (ลงชื่อ).........................................ผู้รับจ้าง</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (...........................................)</span> <span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (นายนิติพัฒน์ วงศ์ศิริธร)</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ผู้รับมอบอำนาจ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
<br><span style="font-weight: 400;">&nbsp;&nbsp;(ลงชื่อ).........................................พยาน</span> <span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (ลงชื่อ).........................................พยาน</span>
<br><span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;(&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;..)&nbsp; </span> <span style="font-weight: 400;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;(นางบุญสวย &nbsp; พรมไพร)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
</div>